// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUNYXaATWVddeVCNENCZLbGK1bLyPQy4k',
    appId: '1:808543726035:web:6d07a42ba584e396366726',
    messagingSenderId: '808543726035',
    projectId: 'apollo-d5a40',
    authDomain: 'apollo-d5a40.firebaseapp.com',
    storageBucket: 'apollo-d5a40.firebasestorage.app',
    measurementId: 'G-FX4E4PHEY4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUNYXaATWVddeVCNENCZLbGK1bLyPQy4k',
    appId: '1:808543726035:web:a0f81bf1a2a8425a366726',
    messagingSenderId: '808543726035',
    projectId: 'apollo-d5a40',
    authDomain: 'apollo-d5a40.firebaseapp.com',
    storageBucket: 'apollo-d5a40.firebasestorage.app',
    measurementId: 'G-YL9SF4FLLM',
  );
}
